assert(g_game.isOnline(),'test login not ready')
modules.client_options.hide()
g_game.talk('!viewportqa reset')
ViewportQA.geometry('FINAL-1366')
g_ui.getRootWidget():setSize({width=1920,height=1080})
ViewportQA.later(2000,function()
  ViewportQA.geometry('FINAL-1920-internal')
  local names=ViewportQA.creatures()
  assert(names.Sam and names.Rat and names['Viewport Peer'],'missing new-area creature')
  modules.game_battle.checkCreatures()
  local battle={}
  for _,b in ipairs(modules.game_battle.battleButtons) do if b:isVisible() and b.creature then battle[b.creature:getName()]=true end end
  assert(battle['Viewport Peer'] and battle.Sam and battle.Rat,'battle missing visible creature')
  ViewportQA.log('FINAL-creatures-battle-PASS')
  g_game.talk('!viewportqa effects')
end)
ViewportQA.later(4000,function()
  local peer=ViewportQA.creatures()['Viewport Peer']
  assert(peer and peer:getPosition().x==1012 and peer:getHealthPercent()==90,'HP/position update')
  ViewportQA.log('FINAL-player-update-PASS')
  g_game.talk('!viewportqa floor8')
end)
ViewportQA.later(6000,function()
  assert(g_game.getLocalPlayer():getPosition().z==8,'floor8 failed')
  ViewportQA.geometry('FINAL-floor8')
  g_game.talk('!viewportqa floor7')
end)
ViewportQA.later(8000,function()
  assert(g_game.getLocalPlayer():getPosition().z==7,'floor7 failed')
  ViewportQA.geometry('FINAL-floor7')
  g_game.getLocalPlayer():autoWalk({x=1010,y=1003,z=7})
end)
ViewportQA.later(15000,function()
  local p=g_game.getLocalPlayer():getPosition()
  assert(p.x==1010 and p.y==1003,'autowalk failed')
  ViewportQA.geometry('FINAL-autowalk')
  g_game.talk('!viewportqa dense')
end)
ViewportQA.later(19000,function()
  ViewportQA.geometry('FINAL-dense')
  for z=0,7 do
    local t=g_map.getTile({x=1030+(7-z),y=1025+(7-z),z=z})
    assert(t and #t:getItems()>=9,'incomplete dense floor '..z)
  end
  ViewportQA.log('FINAL-eight-dense-floors-PASS')
  g_game.talk('!viewportqa reset')
  modules.client_options.setOption('leftPanels',2)
  modules.client_options.setOption('rightPanels',2)
end)
ViewportQA.later(21000,function()
  ViewportQA.geometry('FINAL-side-panels')
  assert(modules.game_interface.gameLeftPanels:getChildCount()==1 and modules.game_interface.gameRightPanels:getChildCount()==2)
  modules.client_options.setOption('gameView',1)
end)
ViewportQA.later(23000,function()
  ViewportQA.dimension(15,11)
  ViewportQA.log('FINAL-classic-PASS')
  modules.client_options.setOption('leftPanels',1)
  modules.client_options.setOption('rightPanels',1)
  modules.client_options.setOption('gameView',2)
  g_ui.getRootWidget():setSize({width=1366,height=960})
end)
ViewportQA.later(25000,function()
  ViewportQA.dimension(19,13); ViewportQA.geometry('FINAL-19x13')
  g_ui.getRootWidget():setSize({width=1490,height=1120})
end)
ViewportQA.later(27000,function()
  ViewportQA.dimension(21,15); ViewportQA.geometry('FINAL-21x15')
  g_window.resize({width=1024,height=700})
end)
ViewportQA.later(29000,function()
  ViewportQA.geometry('FINAL-resize')
  g_window.setFullscreen(true)
end)
ViewportQA.later(31000,function()
  assert(g_window.isFullscreen()); ViewportQA.geometry('FINAL-fullscreen')
  g_window.setFullscreen(false)
end)
ViewportQA.later(33000,function()
  ViewportQA.geometry('FINAL-fullscreen-exit')
  modules.client_options.show()
  local win=g_ui.getRootWidget():recursiveGetChildById('optionsWindow')
  local tabs=win:getChildById('optionsTabBar')
  tabs:selectTab(tabs:getTab('Interface'))
  ViewportQA.log('FINAL_SUITE_COMPLETE')
end)
